GET http://localhost:80/api/item?id=99
Accept: application/json

###
GET https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid=24f20976ca9c63a1038e8a5a72197f92
Accept: application/json

###
GET https://api.openweathermap.org/geo/1.0/direct?q=London&limit=5&appid=24f20976ca9c63a1038e8a5a72197f92
Accept: application/json

###
